In [7]:
# Onley execuite this cell when the notebook in google colab

# from google.colab import data_table
# data_table.enable_dataframe_formatter()

## Panda DataFrames Part-1 

### Create and grab info from DataFrame

In [8]:
import numpy as np
import pandas as pd

In [9]:
from numpy.random import randn

More about the random.seed() [here](https://www.geeksforgeeks.org/random-seed-in-python/)

In [10]:
np.random.seed(101)

In [11]:
df = pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [12]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [13]:

df['W']  # accesing using coloum.

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [14]:
df[['W','Z']]

          W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [15]:
df['New'] = df['Z'] + df['Y']

In [16]:
df

          W         X         Y         Z       New
A  2.706850  0.628133  0.907969  0.503826  1.411795
B  0.651118 -0.319318 -0.848077  0.605965 -0.242112
C -2.018168  0.740122  0.528813 -0.589001 -0.060187
D  0.188695 -0.758872 -0.933237  0.955057  0.021819
E  0.190794  1.978757  2.605967  0.683509  3.289476

In [17]:
df.drop('New',axis=1) # axis refers to 0 is rows and 1 is to coloum.

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [18]:
df

          W         X         Y         Z       New
A  2.706850  0.628133  0.907969  0.503826  1.411795
B  0.651118 -0.319318 -0.848077  0.605965 -0.242112
C -2.018168  0.740122  0.528813 -0.589001 -0.060187
D  0.188695 -0.758872 -0.933237  0.955057  0.021819
E  0.190794  1.978757  2.605967  0.683509  3.289476

In [19]:
df.drop('New',axis=1, inplace=True)

In [20]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [21]:
df.drop('E',axis=0)

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [22]:
df.shape

(5, 4)

In [23]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [24]:
#Seclecting row
# print(type(df.loc['A']))
print('There is 2 way to access the ROWS (.loc)->location and (.iloc)->index location')
print(df.loc['C'])
print(df.iloc[2])

There is 2 way to access the ROWS (.loc)->location and (.iloc)->index location
W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64
W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

In [25]:
df.loc['B','Y']

-0.8480769834036315

In [26]:
df.loc[['A','B'],['W','Y']]

          W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

## Panda DataFrames Part-2
### Conditional Selections and Multi-Index of DataFrame

In [27]:
#conditional secections
bool_df = df > 0

In [28]:
df[bool_df]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [29]:
df['W'] > 0

A     True
B     True
C    False
D     True
E     True
Name: W, dtype: bool

In [30]:
df[df['W']>0] #-> that means value of coloum 'W' where value is greater then zero. Return the intire row.

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [31]:
df[df['Z'] < 0] #-> that means value of coloum 'Z' where value is less then zero. Return intire row.

          W         X         Y         Z
C -2.018168  0.740122  0.528813 -0.589001

In [32]:
resultdf = df[df['W']>0]

In [33]:
resultdf['X']

A    0.628133
B   -0.319318
D   -0.758872
E    1.978757
Name: X, dtype: float64

In [34]:
df[df['W']>0]['X']

A    0.628133
B   -0.319318
D   -0.758872
E    1.978757
Name: X, dtype: float64

In [35]:
df[df['W']>0][['Y','X']]

          Y         X
A  0.907969  0.628133
B -0.848077 -0.319318
D -0.933237 -0.758872
E  2.605967  1.978757

In [36]:
boolser = df['W']>0
result = df[boolser]
mycols = ['Y','X']
result[mycols]

          Y         X
A  0.907969  0.628133
B -0.848077 -0.319318
D -0.933237 -0.758872
E  2.605967  1.978757

In [37]:
cond = (df['W']>0) & (df['Y']>1)
print('1st way:\n',df[cond])
#same as 
print('2nd way:\n',df[(df['W']>0) & (df['Y']>1)])

1st way:
           W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509
2nd way:
           W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

## More Multi-Index

In [39]:
# Reset to default 0,1...n index
df.reset_index()
df.reset_index(inplace = True)

In [40]:
df

  index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [43]:
newidx = "CA NY WY OR CO".split()
print(newidx)

['CA', 'NY', 'WY', 'OR', 'CO']

In [42]:
df['States'] = newidx

In [44]:
df

  index         W         X         Y         Z States
0     A  2.706850  0.628133  0.907969  0.503826     CA
1     B  0.651118 -0.319318 -0.848077  0.605965     NY
2     C -2.018168  0.740122  0.528813 -0.589001     WY
3     D  0.188695 -0.758872 -0.933237  0.955057     OR
4     E  0.190794  1.978757  2.605967  0.683509     CO

In [45]:
newdf = df

In [49]:
newdf.drop('index', axis=1)
newdf.set_index('States') #for seting the new index 
# newdf.set_index('States',inplace= True)

       index         W         X         Y         Z
States
CA         A  2.706850  0.628133  0.907969  0.503826
NY         B  0.651118 -0.319318 -0.848077  0.605965
WY         C -2.018168  0.740122  0.528813 -0.589001
OR         D  0.188695 -0.758872 -0.933237  0.955057
CO         E  0.190794  1.978757  2.605967  0.683509

In [50]:
newdf

  index         W         X         Y         Z States
0     A  2.706850  0.628133  0.907969  0.503826     CA
1     B  0.651118 -0.319318 -0.848077  0.605965     NY
2     C -2.018168  0.740122  0.528813 -0.589001     WY
3     D  0.188695 -0.758872 -0.933237  0.955057     OR
4     E  0.190794  1.978757  2.605967  0.683509     CO

## Panda DataFrames Part-3
### Multi-Index and Index Hierarchy

In [51]:
#index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [55]:
list(zip(outside,inside))

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [54]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [73]:
df = pd.DataFrame(randn(6,3),hier_index,['A','B','C'])
randn(6,3) #Random number form normal distributions of 6 rows and 3 coloums

array([[ 1.25990369, -0.44789835,  0.26620678],
       [ 0.41258016,  0.98877285,  0.51383273],
       [-0.92820483,  0.8469039 , -0.29843574],
       [ 0.02914148,  0.88903088, -1.83926086],
       [ 0.8635956 , -1.0765905 , -0.58038298],
       [ 1.20902728,  1.20174403, -0.82046316]])

In [74]:
df

             A         B         C
G1 1 -0.034432  0.688408  0.081523
   2 -0.415191  0.053661 -2.115113
   3 -0.279510  1.062710  1.752014
G2 1  0.695547  0.153661  0.167638
   2 -0.765930  0.962299  0.902826
   3 -0.537909 -1.549671  0.435253

In [75]:
df.loc['G1']

          A         B         C
1 -0.034432  0.688408  0.081523
2 -0.415191  0.053661 -2.115113
3 -0.279510  1.062710  1.752014

In [78]:
df.loc['G1'].loc[1]

A   -0.034432
B    0.688408
C    0.081523
Name: 1, dtype: float64

In [79]:
df.index.names

FrozenList([None, None])

In [80]:
df.index.names = ['Groups','Number']
df

                      A         B         C
Groups Number
G1     1      -0.034432  0.688408  0.081523
       2      -0.415191  0.053661 -2.115113
       3      -0.279510  1.062710  1.752014
G2     1       0.695547  0.153661  0.167638
       2      -0.765930  0.962299  0.902826
       3      -0.537909 -1.549671  0.435253

In [84]:
df.index.names

FrozenList(['Groups', 'Number'])

In [83]:
print(df.loc['G2'].loc[2]['B'])
#same as
print(df.loc['G2'].loc[2].loc['B'])
print(df.loc['G1'].loc[3].loc['A'])

0.9622991701503001
0.9622991701503001
-0.27951021452358354

In [89]:
print(df.loc['G1'])
df.xs('G1')    # .xs(index names..)

               A         B         C
Number
1      -0.034432  0.688408  0.081523
2      -0.415191  0.053661 -2.115113
3      -0.279510  1.062710  1.752014
               A         B         C
Number
1      -0.034432  0.688408  0.081523
2      -0.415191  0.053661 -2.115113
3      -0.279510  1.062710  1.752014

               A         B         C
Number
1      -0.034432  0.688408  0.081523
2      -0.415191  0.053661 -2.115113
3      -0.279510  1.062710  1.752014

In [97]:
df.xs(2,level='Number')

               A         B         C
Groups
G1     -0.415191  0.053661 -2.115113
G2     -0.765930  0.962299  0.902826